### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by HaoQChen** [Rockyzsu/stock#19]
一些关键的设置文件是不是被gitignore了？如果怕个人信息泄露的话可以给一个template，加您QQ了

**Comment by zhao305149619** [comment]
故意的，开源的总会留一点尾巴，不然怎么挣钱。

**Comment by iawes** [comment]
> 
> 
> 一些关键的设置文件是不是被gitignore了？如果怕个人信息泄露的话可以给一个template，加您QQ了

还需要配置文件啊？

**Comment by horysk** [comment]
需要配置 setting,

**Comment by Rockyzsu** [comment]
个人配置信息，加上了。
原来是设置个门槛，避免一些白嫖档。 真正稍微对python有点入门的，加个配置文件不难吧？
