### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by zhangdexian** [Rockyzsu/stock#22]
能不能不把一些必要的配置文件隐藏了，能开源大家一起学习交流很感谢，但能真诚一点吗。。

**Comment by rooho** [comment]
怎么你不付钱还想白嫖？(狗头)

**Comment by rooho** [comment]
> 能不能不把一些必要的配置文件隐藏了，能开源大家一起学习交流很感谢，但能真诚一点吗。。

怎么你不付钱还想白嫖？(狗头)

**Comment by Rockyzsu** [comment]
配置文件只是数据库地址，大部分有点经验的都会改的
