### ISSUE TITLE
跑不动

### ISSUE THREAD

**Issue by standyyyy** [Rockyzsu/stock#25]
好像缺配置一个都跑不动

**Comment by andy-wg** [comment]
现在跑起来了吗？我也想跑这个

**Comment by standyyyy** [comment]
跑不了 ，缺少配置 。

**Comment by Rockyzsu** [comment]
#[400](https://github.com/Rockyzsu/stock/commit/40054e1eb0c1d259113b9126b38e9e3794b82d18)

配置文件添加以及使用，主要是一些数据库用户名密码
